### ISSUE TITLE
pressing reset fixes LAeq(1s) to zero

### ISSUE THREAD

**Issue by twest820** [Arpapiemonte/openoise-meter#8] opened 2023-08-30 19:49 UTC
In recent builds pressing reset causes subsequent LAeq(1s) samples to be read as 0.0 dB(A). This seems to fix LAeq(t) at its last recorded value. Affects at least 3.0.4 and 3.0.7-beta, observed on Android 9 with S8.

There's an easy workaround as pressing reset a second time restores functionality. One press of reset sufficed in OpeNoise 2.0.3 and I didn't see this behavior with 3.0.3 on Android 13 with S21.

**Comment by Arpapiemonte** [comment] 2023-08-31 09:57
Sorry we can't understand the issue.
Can you explain better and / or give an example?
Is it a problem in the log file or in the visualization data in the noise meter home page?
Thanks

**Comment by twest820** [comment] 2023-08-31 18:33
Both. Should be easy to repro as all that's needed is to press reset, after which it's obvious in the UX that actual sampling's stopped even though updates continue at 1 Hz.

Here's a brief log from 3.0.7-beta showing the 0.0 dB(A) LAeq(1s) and stuck LAeq(t) in response to a first reset press and then apparent resumption of normal functionality after a second press.
<details><summary>Details</summary>
<p>
Date,Time,LAeq(t),LAeq(1s)<br>
31/08/2023,11:26:53.586,43.8,39.2<br>
31/08/2023,11:26:54.538,43.5,30.8<br>
31/08/2023,11:26:57.484,29.8,0.0<br>
31/08/2023,11:26:58.484,29.8,0.0<br>
31/08/2023,11:26:59.483,29.8,0.0<br>
31/08/2023,11:27:00.483,29.8,0.0<br>
31/08/2023,11:27:01.483,29.8,0.0<br>
31/08/2023,11:27:02.484,29.8,0.0<br>
31/08/2023,11:27:05.126,32.7,32.9<br>
31/08/2023,11:27:06.126,33.2,33.8<br>
31/08/2023,11:27:07.126,33.4,34.2<br>
31/08/2023,11:27:08.174,33.7,34.3<br>
31/08/2023,11:27:09.126,33.8,34.5<br>
31/08/2023,11:27:10.126,33.7,32.9<br>
31/08/2023,11:27:11.127,33.7,33.6<br>
</p>
</details>

**Comment by Arpapiemonte** [comment] 2023-09-07 10:56
Hi, we close this issue as we study the error in the other issue connected to the 1 s samples error ( #6 ).
You have to understand that every device is different, your device has this error, any device we tried has this error.
So it's no easy for us to reproduce it!

**Closed as completed by Arpapiemonte** 2023-09-07 10:56 UTC

**Comment by Arpapiemonte** [comment] 2023-10-02 10:34
Hi @twest820 ,
we are sorry but we cannot reproduce this error in any device (more than 30 devices), nor other people noticed it from the Stores.
So we can't test your error and solve it.
We mantain close the issue until another device shows this error.

Here a video to show you that in our phones all is right:
https://github.com/Arpapiemonte/openoise-meter/assets/7060039/ccf0935b-5f5e-4201-8a58-0146ea6958c2

Here the relative measurement file:
[2023-10-02-122326.txt](https://github.com/Arpapiemonte/openoise-meter/files/12781862/2023-10-02-122326.txt)
